---
title: "lab10-yowsean-li"
author: "Yowsean Li"
date: "11/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
head(USArrests)
```
```{r}
states <- rownames(USArrests)
head(states)
```

```{r}
num_chars <- nchar(states)
num_chars
```

```{r}
tolower(states)
```
```{r}
toupper(states)
```
```{r}
casefold(states, upper=TRUE)
```
```{r}
casefold(states, upper=FALSE)
```

```{r}
char_freqs <- prop.table(num_chars)
barplot(char_freqs)
```

```{r}
paste('Pumpkin', 'Pie')
```

```{r}
paste(states[(0:5)], num_chars[(0:5)], sep="=")
```

```{r}
paste(states[(0:5)], collapse='')
```
```{r}
substr(states, 1, 3)
```

```{r}
paste(substr(states, 1, 1), substr(states, num_chars - 2, num_chars), sep='')
```

```{r}
paste(states[num_chars == 4], collapse = ", ")
```

```{r}
states_list = c()
i <- 0
for (len in 3:max(num_chars)) {
  if (len %% 2 == 0) {
    states_list[i] <- paste(toupper(states[num_chars == len]), collapse = ", ")
    i <- i + 1
  } else {
    states_list[i] <- paste(tolower(states[num_chars == len]), collapse = ", ")
    i <- i + 1
  }
}
names(states_list) = paste((min(num_chars):(max(num_chars))), 'chars', sep='-')
states_list
```

```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5/9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5/9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4/9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  to <- tolower(to)
  switch(to,
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}
temp_convert(30, 'celsius')
temp_convert(30, 'Celsius')
temp_convert(30, 'CELSIUS')
```

```{r}
v1 <- c('file1.csv', 'file2.csv', 'file3.csv', 'file4.csv', 'file5.csv', 'file6.csv', 'file7.csv', 'file8.csv', 'file9.csv', 'file10.csv')
v2 <- paste(paste('file', 1:10, sep=''), '.csv', sep='')
v3 <- paste('file', paste(1:10, '.csv', sep=''), sep='')
v1
v2
v3
```

```{r}
gsub('file', 'dataset', v1)
```

```{r}
# name of output file
outfile <- "output.txt"

# writing to 'outfile.txt'
cat("---", file = outfile)
cat("\n", file = outfile, append = TRUE)
cat("title: Lab 10", file = outfile, append=TRUE)
cat("\n", file = outfile, append = TRUE)
cat("author: Yowsean Li", file = outfile, append=TRUE)
cat("\n", file = outfile, append = TRUE)
cat("date: 11/2/2017", file = outfile, append=TRUE)
cat("\n", file = outfile, append = TRUE)
cat("output: html_document", file=outfile, append=TRUE)
cat("\n", file = outfile, append = TRUE)
cat("---", file = outfile, append=TRUE)
cat("\n\n", file = outfile, append = TRUE)
cat("This is the first line", file = outfile, append=TRUE)
# insert new line
cat("\n", file = outfile, append = TRUE)
cat("A 2nd line", file = "output.txt", append = TRUE)
# insert 2 new lines
cat("\n\n", file = outfile, append = TRUE)
cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

```{r}
is_color <- function(color) {
  Rcolors <- colors()
  tolower(color) %in% Rcolors
}
is_color('yellow')  # TRUE

is_color('blu')     # FALSE

is_color('turkuoise') # FALSE
```

```{r}
colplot <- function(col) {
  if (is_color(col)) {
    plot(runif(10, 0, 1), main=paste('Testing color', col))
  } else {
    print(paste('Invalid color', col))
  }
}
# this should plot
colplot('tomato')

# this stops with error message
colplot('tomate')
```
```{r}
# random vector of letters
set.seed(1)
letrs <- sample(letters, size = 100, replace = TRUE)
head(letrs)

letrcounts <- table(letrs)
vowels <- letrcounts[names(letrcounts) == 'a' |names(letrcounts) == 'e' |names(letrcounts) == 'i' |names(letrcounts) == 'o' |names(letrcounts) == 'u']
vowels
consonants <- letrcounts[names(letrcounts) != 'a' &names(letrcounts) != 'e' &names(letrcounts) != 'i' &names(letrcounts) != 'o' &names(letrcounts) != 'u']
consonants
```

```{r}
count_letters <- function(list) {
  letters <- length(list)
  vowels <- 0
  consonants <- 0
  for (l in list) {
    if (l == 'a'|l=='e'|l=='i'|l=='o'|l=='u') {
      vowels <- vowels + 1
    } else {
      consonants <- consonants + 1
    }
  }
  print(paste('letters:', letters))
  print(paste('vowels:', vowels))
  print(paste('consonants:', consonants))
}
count_letters(letrs)
```

